//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvoiCommandeCRM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.99.247:82/vplanning/resourceimport.do?PLANNING=VP+GROUPE+ADINFO&IM" +
            "PORT=Commandes+de+l%27intranet")]
        public string LienPlanning {
            get {
                return ((string)(this["LienPlanning"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.99.247:82/vplanning/resourceimport.do?PLANNING=VP+GROUPE+ADINFO&IM" +
            "PORT=C765-025B-00E1-0E1B-1C31-FC4F-9003-500B")]
        public string LienPlanningClient {
            get {
                return ((string)(this["LienPlanningClient"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MACLESECRETE")]
        public string Cle_Token {
            get {
                return ((string)(this["Cle_Token"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=SQLNCLI11;Data Source=ARTHURPAJOT\\SQLEXPRESS;Password=vpuser;User ID=vpu" +
            "ser;Initial Catalog=\"VP GROUPE ADINFO\";MultipleActiveResultSets=True")]
        public string VPConnectionString {
            get {
                return ((string)(this["VPConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://crm.groupeadinfo.org")]
        public string URL_Aditiger {
            get {
                return ((string)(this["URL_Aditiger"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=SQLNCLI11;Data Source=ARTHURPAJOT\\SQLEXPRESS;User ID=usertest;Password=p" +
            "assword2,;Initial Catalog=TRANSFERT_VP_backup_2024_04_28_212502_2624838;Packet S" +
            "ize=4096;MARS Connection=True")]
        public string VpTranferConnectionString {
            get {
                return ((string)(this["VpTranferConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=SQLNCLI11;Data Source=ARTHURPAJOT\\SQLEXPRESS;User ID=usertest;Password=p" +
            "assword2,;Initial Catalog=grpediffx5_backup_2024_04_28_213001_2305652;Packet Siz" +
            "e=4096;MARS Connection=True")]
        public string GrpDiffConnectionString {
            get {
                return ((string)(this["GrpDiffConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=ARTHURPAJOT\\SQLEXPRESS;user=usertest;database=crm_cperfor;port=1433;passwo" +
            "rd=password2")]
        public string MySQLConnectionString {
            get {
                return ((string)(this["MySQLConnectionString"]));
            }
        }
    }
}
